import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Clients from '../components/sections/Clients'
import Designer from '../components/sections/Designer'
import Hero from '../components/sections/Hero'
import Marketing from '../components/sections/Marketing'
import Partners from '../components/sections/Partners'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create  Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Marketing />
      <Clients />
      <Partners />
      <Designer />
      <div className='mx-auto bg-orange flex justify-center text-center items-center py-12'>
        <Link href="/contact">
          <h3 className='text-white font-sans text-5xl font-black leading-[3.375rem] max-w-sm md:max-w-md lg:max-w-lg flex  flex-wrap'>🙋 How can we help?</h3>
        </Link>
      </div>
    </>
  )
}
